### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by devanandersen** [devanandersen/env#1]
Things to add:
  * Nix
  * Terminal agnostic (tmux)
  * Remove init.sh if statements and add direct installs through nix instead

**Comment by dv-blk** [comment]
did you try (in order):
- turning it off
- turning it on

**Comment by devanandersen** [comment]
> did you try (in order):
> 
>     * turning it off
> 
>     * turning it on

Feel free to submit a PR

**Comment by devanandersen** [comment]
> did you try (in order):
> 
>     * turning it off
> 
>     * turning it on

@dv-blk feel free to submit a PR

**Comment by dv-blk** [comment]
okay i'm going to:
- remove all of the code
- PR with said code
